#!/usr/bin/python
# Moves a containter to the workspace with the given number and changes the current workspace to it
import i3ipc
from sys import argv
i3  = i3ipc.Connection()

focused = i3.get_tree().find_focused()
focused.command(f"move container to workspace number {argv[-1]}")
i3.command(f"workspace number {argv[-1]}")
